apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
    spec:
      initContainers:
      - name: ensure-clean-init
        image: alpine:latest
        command:
          - sh
          - -c
          - |
            echo "Checking for existing PostgreSQL database..."
            if [ -f /data/18/docker/PG_VERSION ]; then
              echo "✓ Found existing database at /data/18/docker/ - preserving data"
            elif [ -f /data/17/docker/PG_VERSION ]; then
              echo "✓ Found existing database at /data/17/docker/ - preserving data"
            elif [ -f /data/16/docker/PG_VERSION ]; then
              echo "✓ Found existing database at /data/16/docker/ - preserving data"
            else
              echo "✗ No existing database found - ensuring clean directory for initialization"
              rm -rf /data/* /data/..?* /data/.[!.]* 2>/dev/null || true
              echo "✓ Directory cleaned - PostgreSQL will run init scripts"
            fi
        volumeMounts:
          - name: postgres-storage
            mountPath: /data
      containers:
      - name: postgres
        image: registry.62.171.153.219.nip.io/postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saasodoo-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        # Service-specific users (for init scripts)
        - name: POSTGRES_AUTH_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saasodoo-secrets
              key: POSTGRES_AUTH_SERVICE_PASSWORD
        - name: POSTGRES_BILLING_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saasodoo-secrets
              key: POSTGRES_BILLING_SERVICE_PASSWORD
        - name: POSTGRES_INSTANCE_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saasodoo-secrets
              key: POSTGRES_INSTANCE_SERVICE_PASSWORD
        - name: POSTGRES_DATABASE_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saasodoo-secrets
              key: POSTGRES_DATABASE_SERVICE_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: postgres-storage
        hostPath:
          path: /mnt/cephfs/postgres_data
          type: DirectoryOrCreate
