# SaaSOdoo Development Docker Compose
# This file provides the main entry point for development
# Use: docker-compose -f infrastructure/compose/docker-compose.dev.yml up
# Or use the Makefile commands: make dev-up

version: '3.8'

# This is a placeholder file that references the main development infrastructure
# The actual services are defined in infrastructure/compose/docker-compose.dev.yml

# To start the development environment, run:
# make dev-up
# 
# Or directly:
# docker-compose -f infrastructure/compose/docker-compose.dev.yml up -d

# Future microservices will be added to infrastructure/compose/docker-compose.dev.yml
# or as separate compose files that can be combined
