---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: docker-registry
    app.kubernetes.io/component: infrastructure
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: docker-registry
