---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisfailovers.databases.spotahome.com
spec:
  group: databases.spotahome.com
  names:
    kind: RedisFailover
    listKind: RedisFailoverList
    plural: redisfailovers
    singular: redisfailover
    shortNames:
      - rf
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sentinel:
                  type: object
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                    customConfig:
                      type: array
                      items:
                        type: string
                redis:
                  type: object
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                            memory:
                              type: string
                    exporter:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                        image:
                          type: string
                        args:
                          type: array
                          items:
                            type: string
                    customConfig:
                      type: array
                      items:
                        type: string
                    storage:
                      type: object
                      properties:
                        keepAfterDeletion:
                          type: boolean
                        persistentVolumeClaim:
                          type: object
                          properties:
                            metadata:
                              type: object
                            spec:
                              type: object
                auth:
                  type: object
                  properties:
                    secretPath:
                      type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Sentinels
          type: integer
          jsonPath: .spec.sentinel.replicas
        - name: Redis
          type: integer
          jsonPath: .spec.redis.replicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
