---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: redis-operator
  labels:
    app.kubernetes.io/name: redis-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator
  labels:
    app.kubernetes.io/name: redis-operator
rules:
  # Redis Operator CRD permissions
  - apiGroups:
      - databases.spotahome.com
    resources:
      - redisfailovers
      - redisfailovers/finalizers
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  # Core resources
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
      - secrets
      - persistentvolumeclaims
    verbs:
      - "*"
  # Apps resources
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - "*"
  # Policy resources
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  # Coordination resources (for leader election)
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-operator
  labels:
    app.kubernetes.io/name: redis-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-operator
subjects:
  - kind: ServiceAccount
    name: redis-operator
    namespace: redis-operator
