---
# Odoo Backups PVC (shared for all instances - dynamic provisioning with Rook CephFS)
# Per-instance storage now uses dedicated PVCs created dynamically
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-backups-pvc
  namespace: saasodoo
  labels:
    app.kubernetes.io/name: instance-service
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 100Gi
