---
# Sealed Secrets Controller
# https://github.com/bitnami-labs/sealed-secrets
#
# This controller decrypts SealedSecret resources into regular Secrets.
# Only this cluster can decrypt secrets sealed with its public key.
#
# Install kubeseal CLI:
#   wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.3/kubeseal-0.27.3-linux-amd64.tar.gz
#   tar xzf kubeseal-0.27.3-linux-amd64.tar.gz
#   sudo mv kubeseal /usr/local/bin/
#
# Usage:
#   kubeseal --format yaml < secret.yaml > sealed-secret.yaml
#   kubectl apply -f sealed-secret.yaml
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/component: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sealed-secrets
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: sealed-secrets-controller
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: docker.io/bitnami/sealed-secrets-controller:0.27.3
          imagePullPolicy: IfNotPresent
          command:
            - controller
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: sealed-secrets
