apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-service-sa
  namespace: saasodoo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-service-role
  namespace: saasodoo
rules:
  # Pods - for checking StatefulSet pod status
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

  # Services - for PostgreSQL pool headless services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]

  # StatefulSets - for PostgreSQL pool management
  - apiGroups: ["apps"]
    resources: ["statefulsets", "statefulsets/scale"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

  # ConfigMaps - for pool configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

  # Events - for debugging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

  # PersistentVolumeClaims - for creating PostgreSQL pool storage
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-service-rolebinding
  namespace: saasodoo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: database-service-role
subjects:
  - kind: ServiceAccount
    name: database-service-sa
    namespace: saasodoo
