global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'saasodoo-dev'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics

  # RabbitMQ Prometheus metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 30s

  # SaaSOdoo Microservices
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'instance-service'
    static_configs:
      - targets: ['instance-service:8003']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'billing-service'
    static_configs:
      - targets: ['billing-service:8004']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend-service:3000']
    metrics_path: /metrics
    scrape_interval: 60s

  # KillBill billing engine
  - job_name: 'killbill'
    static_configs:
      - targets: ['killbill:8080']
    metrics_path: /metrics
    scrape_interval: 60s 