# CloudNativePG Operator Installation Reference
#
# Apply CloudNativePG Operator from official repository:
# Version: v1.28.0 (latest stable as of Dec 2025)
#
# Installation command:
# kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.28/releases/cnpg-1.28.0.yaml
#
# This creates:
# - Namespace: cnpg-system
# - CRDs: Cluster, Backup, ScheduledBackup, Pooler, ImageCatalog
#   - postgresql.cnpg.io (Cluster CR)
#   - backup.cnpg.io (Backup CR)
#   - scheduledbackup.cnpg.io (ScheduledBackup CR)
#   - pooler.cnpg.io (Pooler CR for PgBouncer)
#   - imagecatalog.cnpg.io (ImageCatalog CR)
# - ServiceAccount: cnpg-manager
# - ClusterRole: cnpg-manager (cluster-wide permissions)
# - ClusterRoleBinding: cnpg-manager-rolebinding
# - Deployment: cnpg-controller-manager (2 replicas)
#   - Image: ghcr.io/cloudnative-pg/cloudnative-pg:1.28.0
#   - Leader election enabled for HA
#   - Webhook server for validation and mutation
#
# Key Features:
# - Manages PostgreSQL clusters with high availability
# - Automatic failover and manual switchover
# - Backup and recovery with barman-cloud (WAL archiving + PITR)
# - Connection pooling via PgBouncer Pooler
# - Monitoring via Prometheus metrics and PodMonitor
# - Certificate management via cert-manager (optional)
# - Continuous WAL archiving for point-in-time recovery
#
# Deployment Steps:
# 1. Apply operator manifest:
#    kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.28/releases/cnpg-1.28.0.yaml
#
# 2. Wait for operator to be ready:
#    kubectl wait --for=condition=Available --timeout=300s deployment/cnpg-controller-manager -n cnpg-system
#
# Verify installation:
# kubectl get deployment -n cnpg-system
# kubectl get pods -n cnpg-system
# kubectl get crds | grep postgresql.cnpg.io
# kubectl logs -n cnpg-system -l app.kubernetes.io/name=cloudnative-pg --tail=50
#
# Operator Configuration:
# The operator watches all namespaces by default and manages Cluster resources.
# No additional configuration needed for basic operation.
#
# Upgrade Instructions:
# To upgrade the operator, apply the new version manifest:
# kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.XX/releases/cnpg-1.XX.X.yaml
#
# Official Documentation:
# https://cloudnative-pg.io/documentation/current/
# https://github.com/cloudnative-pg/cloudnative-pg
