---
# ConfigMap with Ceph Monitor Endpoints
# This tells Rook how to connect to the external Ceph cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  # Monitor endpoints (MON addresses from your Ceph cluster)
  data: |
    vmi2887102=10.0.0.2:6789
    vmi2887101=10.0.0.1:6789
    vmi2887103=10.0.0.3:6789
  # Mapping of monitor names to addresses
  mapping: |
    {
      "node": {
        "vmi2887102": {"Name": "vmi2887102", "Hostname": "vmi2887102", "Address": "10.0.0.2"},
        "vmi2887101": {"Name": "vmi2887101", "Hostname": "vmi2887101", "Address": "10.0.0.1"},
        "vmi2887103": {"Name": "vmi2887103", "Hostname": "vmi2887103", "Address": "10.0.0.3"}
      }
    }
  maxMonId: "2"
  # CSI cluster configuration for CephFS and RBD drivers
  csi-cluster-config-json: |
    [
      {
        "clusterID": "3d6c6993-c608-11f0-9f68-0050565df5d5",
        "monitors": [
          "10.0.0.2:6789",
          "10.0.0.1:6789",
          "10.0.0.3:6789"
        ],
        "cephFS": {
          "subvolumeGroup": ""
        }
      }
    ]
---
# Secret with Ceph Cluster FSID and Admin Credentials
# Contains the Ceph cluster ID and monitor secret
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-mon
  namespace: rook-ceph
type: Opaque
stringData:
  # Ceph cluster name (can be any identifier)
  cluster-name: saasodoo-ceph-external
  # Ceph cluster FSID (from: ceph fsid)
  fsid: 3d6c6993-c608-11f0-9f68-0050565df5d5
  # Admin keyring (from: ceph auth get client.admin)
  mon-secret: AQA5BR9pIBWGERAAH1kMgbC8hdv2f2AYCye8JA==
---
# Secret with Ceph Admin Keyring
# Full keyring with capabilities for cluster management
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-admin-keyring
  namespace: rook-ceph
type: Opaque
stringData:
  keyring: |
    [client.admin]
        key = AQA5BR9pIBWGERAAH1kMgbC8hdv2f2AYCye8JA==
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
---
# Secret for CSI CephFS Provisioner
# Used by CSI driver to provision CephFS volumes
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph
type: Opaque
stringData:
  # Admin ID and key for volume provisioning
  adminID: admin
  adminKey: AQA5BR9pIBWGERAAH1kMgbC8hdv2f2AYCye8JA==
---
# Secret for CSI CephFS Node Plugin
# Used by CSI driver to mount CephFS volumes on nodes
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph
type: Opaque
stringData:
  # Admin ID and key for mounting volumes
  adminID: admin
  adminKey: AQA5BR9pIBWGERAAH1kMgbC8hdv2f2AYCye8JA==
